---
- name: Start Watchtower
  when: watchtower_enabled
  block:
    - name: Check for Watchtower Breaking Changes
      ansible.builtin.include_role:
        name: breaking_changes
      vars:
        breaking_changes_application: watchtower

    - name: Watchtower Docker Container
      community.docker.docker_container:
        name: "{{ watchtower_container_name }}"
        image: "{{ watchtower_image_name }}:{{ watchtower_image_version }}"
        pull: true
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        env: >-
          {{
            {'TZ': computer_timezone}
            | combine({'WATCHTOWER_HTTP_API_METRICS': 'true',
                       'WATCHTOWER_HTTP_API_TOKEN': watchtower_metrics_token}
                      if watchtower_metrics_enabled else {})
            | combine({'WATCHTOWER_EPHEMERAL_SELF_UPDATE': 'true'}
                      if watchtower_ephemeral_self_update_enabled else {})
          }}
        command: "{{ watchtower_command }}"
        ports: "{{ ['%d:8080' | format(watchtower_metrics_port | int)] if watchtower_metrics_enabled else omit }}"
        restart_policy: unless-stopped
        memory: "{{ watchtower_memory }}"

- name: Stop Watchtower
  when: not watchtower_enabled
  block:
    - name: Stop Watchtower
      community.docker.docker_container:
        name: "{{ watchtower_container_name }}"
        state: absent
