{
 "title": "Ansible-Homelab-Orchestration Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(system_uptime,host)"
    }
   },
   {
    "name": "zfs_pool",
    "label": "ZFS Pool",
    "query": {
     "query": "label_values(zfs_pool_reads,pool)"
    }
   },
   {
    "name": "physical_disk",
    "label": "Physical Disk",
    "query": {
     "query": "label_values(diskio_reads,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime{host=\"$server\"}"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_n_cpus{host=\"$server\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{host=\"$server\",cpu=\"cpu-total\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_total{host=\"$server\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_used_percent{host=\"$server\"}"
    }
   ]
  },
  {
   "title": "RootFS used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used_percent{host=\"$server\",path=\"/\"}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "swap_used_percent{host=\"$server\"}"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_n_containers_running{host=\"$server\"}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_user{host=\"$server\",cpu=\"cpu-total\"}",
     "legendFormat": "user"
    },
    {
     "expr": "cpu_usage_system{host=\"$server\",cpu=\"cpu-total\"}",
     "legendFormat": "system"
    },
    {
     "expr": "cpu_usage_iowait{host=\"$server\",cpu=\"cpu-total\"}",
     "legendFormat": "iowait"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load1{host=\"$server\"}",
     "legendFormat": "load1"
    },
    {
     "expr": "system_load5{host=\"$server\"}",
     "legendFormat": "load5"
    },
    {
     "expr": "system_load15{host=\"$server\"}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mem_used{host=\"$server\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "mem_cached{host=\"$server\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "mem_buffered{host=\"$server\"}",
     "legendFormat": "Buffered"
    }
   ]
  },
  { "title": "Docker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{host=\"$server\",cpu=\"cpu-total\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_usage{host=\"$server\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "System Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "sensors_temp_input{host=\"$server\"}",
     "legendFormat": "{{chip}} {{feature}}"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "hddtemp_temperature{host=\"$server\",device=~\"$physical_disk\"}",
     "legendFormat": "{{device}} - {{model}}"
    }
   ]
  },
  { "title": "ZFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Pool $zfs_pool Data I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "repeat": "zfs_pool",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(zfs_pool_nread{host=\"$server\"}[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(zfs_pool_nwritten{host=\"$server\"}[$__rate_interval]) * -1",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Pool $zfs_pool Iops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "repeat": "zfs_pool",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(zfs_pool_reads{host=\"$server\"}[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(zfs_pool_writes{host=\"$server\"}[$__rate_interval]) * -1\n",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "Physical Disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "$physical_disk Data I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "repeat": "physical_disk",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_read_bytes{host=\"$server\",name=~\"$physical_disk\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(diskio_write_bytes{host=\"$server\",name=~\"$physical_disk\"}[$__rate_interval]) * -1",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "$physical_disk Disk Iops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "repeat": "physical_disk",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_reads{host=\"$server\",name=\"$physical_disk\"}[$__rate_interval])",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(diskio_writes{host=\"$server\",name=\"$physical_disk\"}[$__rate_interval]) * -1",
     "legendFormat": "Writes"
    }
   ]
  },
  { "title": "Disk SMART", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Power On Hours",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_power_on_seconds / 3600",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Power Cycle Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "smartctl_device_power_cycle_count",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Start Stop Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "smartctl_device_attribute{attribute_name=\"Start_Stop_Count\", attribute_value_type=\"raw\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Internet Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Internet Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "last_over_time(speedtest_download_bits_per_second[65m])",
     "legendFormat": "Download"
    },
    {
     "expr": "last_over_time(speedtest_upload_bits_per_second[65m])",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Internet Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "last_over_time(speedtest_ping_latency_milliseconds[65m])",
     "legendFormat": "Latency"
    }
   ]
  }
 ]
}